### ISSUE TITLE
upgrade 5.8~ynh1 -> 6.1.1~ynh1 is failing

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/wordpress_ynh#212]
### Describe the bug

upgrade is failing

### Context

- Hardware: *VPS*
- YunoHost version:
```
yunohost: 
  repo: stable
  version: 11.1.13
yunohost-admin: 
  repo: stable
  version: 11.1.7
moulinette: 
  repo: stable
  version: 11.1.4
ssowat: 
  repo: stable
  version: 11.1.4
```
- I have access to my server: 
*Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: 
*no*
- Using, or trying to install package version/branch: 
`6.1.1~ynh1`
- If upgrading, current package version: 
`5.8~ynh1`

### Steps to reproduce

- *command from the CLI*
    ```sh
    # yunohost app upgrade wordpress__4
    ```
### Expected behavior
wp should upgrade into main wp_ynh release 6.1.1~ynh1

### Logs
https://paste.yunohost.org/raw/hasimoniji

thx for your help <3
