### ISSUE TITLE
Problem with php-fpm and php7

### ISSUE THREAD

**Issue by nathanael-h** [YunoHost-Apps/wordpress_ynh#50]
Hello, 
I tried to update wordpress from the cli and it failed. The backup could not be restore after this first failure. 
Then I tried a few things and manage to restore the pre-update-bakcup. 
But I had a **502 Bad Gateway error**. 
I solved the error changing a line in : 
`/etc/php/7.0/fpm/pool.d/wordpress__2.conf`
From : 
`listen = /var/run/php5-fpm-wordpress__2.sock`
To :
`listen = /run/php/php7.0-fpm-wordpress__2.sock`

So my problem seems to be solved. But I think this should be handled by the install, update, restore scripts. 

My server is a kimsufi VPS. I was running this version before trying to update apps.
```
yunohost:  
    repo: stable  
    version: 3.1.0
yunohost-admin:  
    repo: stable  
    version: 3.1.0
moulinette:  
    repo: stable  
    version: 3.1.0
ssowat:  
    repo: stable  
    version: 3.1.0
```
