### ISSUE TITLE
failed on update + removed my 2 wp 

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/wordpress_ynh#57]
hi, 
my last update was yesterday without any trouble, 
but today, the update removed my 2 wordpress and i needed to restart php-fpm ...
restoration failed (via webadmin)

```
root@krashboyz:/home/isaaac# yunohost -v
yunohost: 
  repo: stable
  version: 3.4.2.4
yunohost-admin: 
  repo: stable
  version: 3.4.2
moulinette: 
  repo: stable
  version: 3.4.2
ssowat: 
  repo: stable
  version: 3.4.2
```
failed update logs : 
https://paste.yunohost.org/raw/basobekopo

failed restoration logs : https://paste.yunohost.org/raw/asametozaw

help needed to restore the 2 wordpress for my users, 
thx
